### ISSUE TITLE
demo 运行不了

### ISSUE THREAD

**Issue by panli889** [laincloud/hello-world#1]
加了 release 之后，cmd 需要做出相应更改

**Comment by panli889** [comment]
@bibaijin

**Comment by bibaijin** [comment]
忘了把本地更改提交上来了。。。现在应该可以了~ @panli889 

有 3 个版本，[v1.0.0](https://github.com/laincloud/hello-world/tree/v1.0.0)，[v2.0.0](https://github.com/laincloud/hello-world/tree/v2.0.0) 和 [v2.1.0](https://github.com/laincloud/hello-world/tree/v2.1.0)，分别是最简单的版本，使用了 redis-service-sm 的和在 lain.yaml 里增加了 prepare、release 字段的~
